### ISSUE TITLE
Window not working

### ISSUE THREAD

**Issue by munshiomar1971** [BJ-Tech/Freeze-Attack#1]
the `window_setup` is showing a lot of problems. Here is the code: 

```Rust
fn main() {
    // create context
    let (mut ctx, mut event_loop) = conf::Conf::new()
        .window_setup(conf::WindowSetup::default().title("Freeze Attack"))
        .window_mode(conf::WindowMode::default().dimensions(800.0, 600.0))
        .build()
        .expect("Could not create ggez context");

    // Set window position here
    let (ref mut ctx, event_loop) = &mut cb.build()?; 
    let window = graphics::window(ctx);
    let mut pos = window.get_position().unwrap();
    pos.x = 0.0;
    pos.y = 0.0;
    window.set_position(pos);
}
```

the `set_position` is also showing problems. Would appreciate for the solution. @NafizTech

**Comment by NafizTech** [comment]
extern crate ggez;
extern crate rand;

use rand::Rng;

use ggez::event;
use ggez::graphics;
use ggez::timer;
use ggez::nalgebra as na;
use ggez::{Context, GameResult};

const WIDTH : f32 = 800.0;
const HEIGHT: f32 = 800.0;
const MAX_DROPS: i32 = 400;
struct Drop {
    x: f32,
    y: f32,
    w: f32,
    h: f32,
    speed: f32
}
impl Drop {
    fn new() -> Drop {
        let mut rng = rand::thread_rng();
        let x : f32 = rng.gen();
        let y : f32 = rng.gen();
        let s : f32 = rng.gen();
        let init_x = x * WIDTH;
        let init_y = -y * HEIGHT;
        let init_speed = s * 10.0 + 50.0;
        Drop {
            x: init_x,
            y: init_y,
            w: 3.0,
            h: 6.0,
            speed: init_speed,
        }
    }
    fn update(&mut self, dt: f32) {
        self.y += self.speed * dt;
        if self.y > HEIGHT {
            let mut rng = rand::thread_rng();
            let y : f32 = rng.gen();
            self.y = -y * HEIGHT;
        }
    }
}

struct MainState {
    drops: Vec<Drop>
}

impl MainState {
    fn new(_ctx: &mut Context) -> GameResult<MainState> {
        let mut all_drops = Vec::new();
        for _i in 0..MAX_DROPS {
            all_drops.push(Drop::new());
        }
        let s = MainState {
            drops: all_drops 
        };
        Ok(s)
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        const FPS: u32 = 30;
        while timer::check_update_time(ctx, FPS) {

            let dt = 1.0 / (FPS as f32);
            for drop in self.drops.iter_mut() {
                drop.update(dt);
            }
        }
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
        for drop in self.drops.iter() {
            if drop.y > 0.0 {
                let rectangle = graphics::Mesh::new_rectangle(
                    ctx,
                    graphics::DrawMode::fill(),
                    graphics::Rect::new(drop.x, drop.y, drop.w, drop.h),
                    graphics::WHITE,)?;

                graphics::draw(ctx, &rectangle, (na::Point2::new(0.0, 0.0),))?;
            }
        }
        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("Space Shooter", "LittleBoxes")
        .window_mode(ggez::conf::WindowMode::default().dimensions(WIDTH, HEIGHT))
        .window_setup(ggez::conf::WindowSetup::default().title("Space Shooter"));
    let (ctx, event_loop) = &mut cb.build()?;
    let state = &mut MainState::new(ctx)?;
    event::run(ctx, event_loop, state)
}

**Comment by NafizTech** [comment]
```
extern crate ggez;
extern crate rand;

use rand::Rng;

use ggez::event;
use ggez::graphics;
use ggez::timer;
use ggez::nalgebra as na;
use ggez::{Context, GameResult};

const WIDTH : f32 = 800.0;
const HEIGHT: f32 = 800.0;
const MAX_DROPS: i32 = 400;
struct Drop {
x: f32,
y: f32,
w: f32,
h: f32,
speed: f32
}
impl Drop {
fn new() -> Drop {
let mut rng = rand::thread_rng();
let x : f32 = rng.gen();
let y : f32 = rng.gen();
let s : f32 = rng.gen();
let init_x = x * WIDTH;
let init_y = -y * HEIGHT;
let init_speed = s * 10.0 + 50.0;
Drop {
x: init_x,
y: init_y,
w: 3.0,
h: 6.0,
speed: init_speed,
}
}
fn update(&mut self, dt: f32) {
self.y += self.speed * dt;
if self.y > HEIGHT {
let mut rng = rand::thread_rng();
let y : f32 = rng.gen();
self.y = -y * HEIGHT;
}
}
}

struct MainState {
drops: Vec
}

impl MainState {
fn new(_ctx: &mut Context) -> GameResult {
let mut all_drops = Vec::new();
for _i in 0..MAX_DROPS {
all_drops.push(Drop::new());
}
let s = MainState {
drops: all_drops
};
Ok(s)
}
}

impl event::EventHandler for MainState {
fn update(&mut self, ctx: &mut Context) -> GameResult {
const FPS: u32 = 30;
while timer::check_update_time(ctx, FPS) {

        let dt = 1.0 / (FPS as f32);
        for drop in self.drops.iter_mut() {
            drop.update(dt);
        }
    }
    Ok(())
}

fn draw(&mut self, ctx: &mut Context) -> GameResult {
    graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
    for drop in self.drops.iter() {
        if drop.y > 0.0 {
            let rectangle = graphics::Mesh::new_rectangle(
                ctx,
                graphics::DrawMode::fill(),
                graphics::Rect::new(drop.x, drop.y, drop.w, drop.h),
                graphics::WHITE,)?;

            graphics::draw(ctx, &rectangle, (na::Point2::new(0.0, 0.0),))?;
        }
    }
    graphics::present(ctx)?;
    Ok(())
}
}

pub fn main() -> GameResult {
let cb = ggez::ContextBuilder::new("Space Shooter", "LittleBoxes")
.window_mode(ggez::conf::WindowMode::default().dimensions(WIDTH, HEIGHT))
.window_setup(ggez::conf::WindowSetup::default().title("Space Shooter"));
let (ctx, event_loop) = &mut cb.build()?;
let state = &mut MainState::new(ctx)?;
event::run(ctx, event_loop, state)
}
```

**Comment by munshiomar1971** [comment]
that only creates more problems @NafizTech
